name: gadm
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.6
  - pip
  - pip:
      - -r requirements.txt

      # environment tools
      - flake8
      - pep8-naming
      - black
      - isort
      - mypy
