on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  test-production:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
           python-version: ${{matrix.python-version}}

      - name: Run tests
        run: |
          pip install . -U
          pip install -r requirements-dev.txt
          python setup.py sdist
          pytest -vv --cov --black --profile
